services:

  nginx:
    image: nginx:latest
    container_name: pizza-city_nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - php
      - mysql
    links:
      - php
      - node

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: pizza-city_php
    volumes:
      - ./:/var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    links:
      - mysql
      - node

  mysql:
    image: mysql:latest
    container_name: pizza-city_mysql
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pizza-city
      - REDIS_HOST=cache
      - REDIS_PORT=6379

  phpmyadmin:
    image: phpmyadmin
    container_name: pizza-city_phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql

  node:
    image: node:latest
    container_name: pizza-city_node
    ports:
        - "3000:3000"
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true
